#! /bin/bash
#
# Exercice 2 : css
#
# author : jclaude
# date : 2022/02/15

out_dir=$1

ls "$out_dir" | grep '.html$' |\
    while read -r html_file; do

        style=`./get_style_content.sh "$out_dir/$html_file"`

        echo "$style" |\
            # only look at stderr
            sass --stdin --no-unicode 2>&1 >/dev/null |\
            # get only the lines which mention the error name
            grep "Error:" |\
        # iterate over error messages, because there might be > 1
        while read -r err_msg; do
            echo "$html_file, $err_msg"
        done
    done