#! /bin/bash
#
# Exercice 2 : css
#
# author : jclaude
# date : 2022/02/15

out_dir=$1

find "$out_dir" -name '*.html' |\
    while read -r file; do
        # need for grep
        no_lines=$(wc -l "$file" | cut -f1 -d' ')

        cat "$file" |\
            # take everything between the style tag
            grep -A "$no_lines" "<style.*>" | grep -B "$no_lines" "</style>" |\
            # put everything on the same line
            sed -z 's/\n/ʕノ•ᴥ•ʔノ ︵ ┻━┻/g' |\
            # get everything in between the first and last tag
            cut -f2- -d ">" | rev | cut -f2- -d "<" | rev |\
            # put the newlines back
            sed -z 's/ʕノ•ᴥ•ʔノ ︵ ┻━┻/\n/g' > .temp.css

        error_msg=`sass .temp.css | grep "Error: "`
        if [[ -n "$error_msg" ]]; then
            echo "$error_msg"
        fi
    done

rm .temp.css