#! /bin/bash
#
#
#
# author : jclaude
# date : 2022/02/19

filenames=$1
out_dir=$2

readarray -d ";" -t filename_arr <<< "$filenames"

for filename in ${filename_arr[@]}
do
    style=`./get_style_content.sh "$filename"`

    echo "#html-result { $style }" |\
        # only look at stdout
        sass --stdin 2> /dev/null > "$filename.css"

    echo "$style" |\
        # only look at stdout
        sass --stdin 2> /dev/null > "$filename.display.css"
done

python transf.py "$filenames" "$out_dir"

cp /template/_index.css "$out_dir/css/_index.css"

for filename in ${filename_arr[@]}
do
    rm "$filename.css" "$filename.display.css"
done